### PR TITLE
add before/after relative date query

### PR DESCRIPTION
**Pull request by petschki**
see #45

### CODE REVIEW

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/271/
even if ok, this is a feature not to merge in RC phase of Plone 5 (so this targets 5.1)

**Comment by petschki** [comment]
so Plone 5.0 versions.cfg pins p.a.querystring to 1.3.6 an we're fine, arent we ?

**Comment by jensens** [comment]
https://github.com/plone/plone.app.querystring/pull/46

**Comment by jensens** [comment]
@petschki please rebase

**Comment by petschki** [comment]
@jensens done

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/355/

**Comment by jensens** [comment]
@esteele this is a small new feature, ok to merge in RC or better for 5.1?

**Comment by esteele** [comment]
@jensens Merge away.

**Pull request merged**
