### PR TITLE
Fixed QuerystringRegistryReader.mapSortableIndex so it doesnt return …

### LINKED ISSUE #37: CatalogError: The index chosen for sort_on (byline) is not capable of being used as a sort index.
The field 'Sort on'  in collection, list index of type 'ZCTextIndex' if the record is placed as 'sortable'. When you create a filter and an index 'ZCTextIndex' is selected in 'Sort on', the error below occurs  in the return of the ajax call (querybuilder_html_results):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module plone.app.querystring.querybuilder, line 58, in html_results
    Module plone.app.querystring.querybuilder, line 49, in __call__
    Module plone.app.querystring.querybuilder, line 116, in _makequery
    Module Products.CMFPlone.CatalogTool, line 393, in searchResults
    Module Products.ZCatalog.ZCatalog, line 604, in searchResults 
    Module Products.ZCatalog.Catalog, line 916, in searchResults
    Module Products.ZCatalog.Catalog, line 894, in _getSortIndex

    CatalogError: The index chosen for sort_on (byline) is not capable of being used as a sort index.

The field 'Sort on' should not list index of type 'ZCTextIndex'.

### PR DESCRIPTION
**Pull request by winstonf88**
closes #37

### CODE REVIEW

**Comment by jensens** [comment]
which Plone versions does this one and #49 target at? Do we need the fix in master as well?

**Comment by jensens** [comment]
ah, sorry, missed #43

**Comment by jensens** [comment]
wait until #43 (targets master) is ok and then proceed with this one too

**Comment by winstonf88** [comment]
@jensens this is also related with #43

**Comment by mauritsvanrees** [comment]
This causes a test failure for archetypes.querywidget:
http://jenkins.plone.org/job/plone-4.3-python-2.7/800/

**Comment by mauritsvanrees** [comment]
Ah, got it. Committing a fix now.

**Comment by mauritsvanrees** [comment]
Fixed in 1445e1209e325a53a4064f0a822df63049ef57b3.

The archetypes.querywidget tests look like they use an index that does not exist but they still get some values out of it. So that test might be dodgy, or using some mock stuff. Anyway, easily fixed in the p.a.querystring code.

**Pull request merged**
