### PR TITLE
Add operators selection.any and selection.all to Subject

### PR DESCRIPTION
**Pull request by MrTango**
change Subject QueryField operators to use selection.oneOf and selection.all
operators. The change make's it possible to use "oneOf" (OR) and "all" (AND) for
Tag criteria of collections. Now is there only a meaningless "Is" operator.

### CODE REVIEW

**Comment by gforcada** [comment]
Running tests on: http://jenkins.plone.org/job/pull-request/82/console

**Comment by djowett** [comment]
+1 for this. Strangely I was just looking at the same issue.
I would recommend to change the English slightly as as tags are not really "contained" in an object:

"Contains one of" -> "Matches one of"
"Contains all" -> "Matches all of"

**Comment by MrTango** [comment]
Your are right. I think i'll spend some time on friday (World Plone Office Day) to finished this and the robot test for plone.app.contenttypes for the collections..

**Comment by djowett** [comment]
Fantastic (and thanks for the reminder)..
I did notice room for more testing while going through the stack for this issue.

**Comment by gforcada** [comment]
Running it again as the previous run did not take off: http://jenkins.plone.org/job/pull-request/87/console

**Comment by jensens** [comment]
looks like there are some migration issues left, see http://jenkins.plone.org/job/pull-request/87/testReport/

**Comment by MrTango** [comment]
yes, i'll check fix that soon.

**Comment by jensens** [comment]
and please rebase :)

**Comment by MrTango** [comment]
http://jenkins.plone.org/view/PLIPs/job/plip-plip-querystring/8/
can be merged now together with follwing pull requests:

- https://github.com/plone/plone.app.contenttypes/pull/245
- https://github.com/plone/mockup/pull/533
- https://github.com/plone/Products.CMFPlone/pull/712
- https://github.com/plone/plone.app.upgrade/pull/38

**Pull request merged**
