### PR TITLE
Use `munge_search_term` from CMFPlone

### PR DESCRIPTION
**Pull request by petschki**
I've brought back the changes from @erral to this new PR for Plone 6 ...

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
The robot failures seem unrelated, but all three jobs failing is a bit much. Let's try again.

@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
oh my ... I've added experimental github actions workflow ... at least 2 coredevs are green ... locally I cannot reproduce the robot failures ...

**Comment by mauritsvanrees** [comment]
We probably should not add GH actions here, so we should remove it before merge. But it is good to know that the 3.9 and 3.10 jobs passed. I restarted the failing actions.
And let's try Jenkins again. There are no other jobs running currently, that may help.

@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
Other than the failing Jenkins tests, and the gh-actions that can be removed, this LGTM.

**Comment by petschki** [comment]
Will do.

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Only 3.7 has unrelated robot failures now. I merge.

**Pull request merged**
