### PR TITLE
1.2.x

### LINKED ISSUE #37: CatalogError: The index chosen for sort_on (byline) is not capable of being used as a sort index.
The field 'Sort on'  in collection, list index of type 'ZCTextIndex' if the record is placed as 'sortable'. When you create a filter and an index 'ZCTextIndex' is selected in 'Sort on', the error below occurs  in the return of the ajax call (querybuilder_html_results):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module plone.app.querystring.querybuilder, line 58, in html_results
    Module plone.app.querystring.querybuilder, line 49, in __call__
    Module plone.app.querystring.querybuilder, line 116, in _makequery
    Module Products.CMFPlone.CatalogTool, line 393, in searchResults
    Module Products.ZCatalog.ZCatalog, line 604, in searchResults 
    Module Products.ZCatalog.Catalog, line 916, in searchResults
    Module Products.ZCatalog.Catalog, line 894, in _getSortIndex

    CatalogError: The index chosen for sort_on (byline) is not capable of being used as a sort index.

The field 'Sort on' should not list index of type 'ZCTextIndex'.

### PR DESCRIPTION
**Pull request by winstonf88**
See pull request: https://github.com/plone/plone.app.querystring/pull/43
closes #37

### CODE REVIEW

**Comment by pbauer** [comment]
What is the purpose of this? It seems (please correct me if I'm wrong) that you actually want to rebase the branch issue_37 on 1.2.x. To do that you'd have to checkout branch issue_37, then ``git rebase 1.2.x``, resolve all conflicts that occur in that process and afterwards do a force-push `` git push -f`` (to also rewrite the history of issue_37 on the server). See also http://buildoutcoredev.readthedocs.org/en/latest/git.html

**Comment by mauritsvanrees** [comment]
Note that a forced push must never be done on master or on a maintenance branch, because forced pushes cause problems for others who already have that branch locally. But on a pull request branch it is fine.

**Comment by idgserpro** [comment]
@winstonf88 it would not be easier create a new branch based on branch 1.2.x and make a cherry pick of commit https://github.com/plone/plone.app.querystring/commit/6ef03795883b0a92aee85eb1b4f5e0a38e4c401e in this new branch?

**Comment by hvelarde** [comment]
@winstonf88 please create a new PR based on the right branch

**Comment by jensens** [comment]
@winstonf88 please sign a Plone Contributor Agreement in order to get your PRs merged. Otherwise ist not possible because of legal reasons.

**Comment by hvelarde** [comment]
@jensens @esteele my mistake: I though I was deleting a branch that should be merged with the 1.2.x branch

**Pull request closed without merging**
