### PR TITLE
Make integer query operators accept unicode values.

### PR DESCRIPTION
**Pull request by lzdych**
Fixes their usage via QueryStringFieldWidget.

### CODE REVIEW

**Comment by jensens** [comment]
Thanks!

Which version does it target at?
I guess we need it on master as well?

May you start the CI tests?

**Comment by lzdych** [comment]
Hi Jensens,
this targets 1.3.x since I was working on Plone 5.0 then I noticed that 1.4.x is in use with Plone 5.1 ;-) .. so let port it to master too as new pull request agains master.

CI tests - can you direct me to some docs how to do this? .. Unfortunately I'm not familiar with this process yet ;-(

**Comment by jensens** [comment]
You can always start a Jenkins test-job on your own to test that your pull request (PR) does not break anything. 

See the process (below my standard answer). For some reason, mr.roboto did not run for this PR. Go directly to http://jenkins.plone.org/job/pull-request-5.0/ and start it from there.

Below click on the link to Jenkins
screenshot from 2016-07-25 11 20 06

**log in** with your Github user - if not already done before.

Paste the full **pull request URL** into the text field (if multiple pull requests need to be combined in one run, then one PR URL per line)

Click on **Build**

Jenkins reports back to the pull request(s) on Github in the status box at the bottom.

In Plone we value a lot our testing suite, so we usually never merge pull requests if they have not been tested by Jenkins first.

**Comment by lzdych** [comment]
Thank you for help the CI tests build is in the queue.

**Comment by jensens** [comment]
merged, thanks!

**Pull request merged**
