### PR TITLE
Add operators selection.oneOf and selection.all

### PR DESCRIPTION
**Pull request by MrTango**
change Subject QueryField operators to use selection.oneOf and selection.all
operators

### CODE REVIEW

**Comment by tisto** [comment]
This pull request breaks some tests: http://jenkins.plone.org/job/pull-request/78/console

@MrTango It would help a lot if you could provide some tests to explain what your changes actually do. It would be also important to know why this change is necessary.

**Comment by MrTango** [comment]
Sure, i'll add test for it. The change make's it possible to use "oneOf" (OR) and "all" (AND) for Tag criteria of collections. Now is there only a meaningless "Is" operator.
About the tests, that is strange, on my machine the same test are failing without my changes and they seem related to some changes in the path criterium.

But i'll will debug too, soon.

**Comment by tisto** [comment]
If this is for collections it would be good if you could add some robot tests in plone.app.contenttypes.

**Comment by thet** [comment]
+ 1 for the OR/AND operator. 
your pull request also contains changes to path operators. it even looks like you're removing features: 
Show Inactive and Navigation path. Can you explain it a bit more?

**Comment by davisagli** [comment]
Kudos for remembering to write an upgrade step. :)

**Comment by MrTango** [comment]
@thet yes you are right, but i don't wanted to touch that, i think i have messed up some thing, i will clean it and try it again.

**Comment by MrTango** [comment]
ok i did another branch "mrtango-subject-all-operator" because my first was messed up some how and i want to start with a clean base. Now the test are passing locally.
I'll do another pull request from the other branch and will close this branch later, if it is ok.
@tisto yes, i'll add some robot test to plone.app.contenttypes, we also need to add my upgrade step to some other package (plone.app.upgrade?), so that it gets triggered.

**Pull request closed without merging**
