### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by lowks**
Adding `description` to `setup.py`

### CODE REVIEW

**Comment by jensens** [comment]
thaks for your contribution. youre not in the list of contributors. so @esteele as release manager can merge this. if you sign the contributor agreement it would be easier for us... if you alreadu did and your name is missing on the list please let us know

**Comment by lowks** [comment]
hi @jensens I have signed, scanned and sent the docs back. Thanks for the heads up.

**Comment by jensens** [comment]
great! welcome :) 
@polyester (btw, are you/ who is responsible?) please ping me if you received it.

**Comment by polyester** [comment]
Andy lieb gets them,  me as well, but I am travelling today

**Comment by polyester** [comment]
Contributor agreement is in.  On phone now, so will add to repo later, but feel free to merge

**Comment by gforcada** [comment]
In then, @lowks welcome to Plone!

**Comment by lowks** [comment]
thanks @gforcada

**Pull request merged**
