### PR TITLE
Config with default template

### PR DESCRIPTION
**Pull request by gforcada**
@ale-rt some tests fail to run because `zpretty` reformatted a few files and added a `utf-8` encoding declaration and `lxml` refuses to parse them as text, but suggests that they should be send to `lxml` as `bytes` rather.

Should we adapt the tests to parse the files as bytes, or rather should `zpretty` not add those `utf-8` encoding declarations? 🤔 

```
Error in test test_get_vocabularies (plone.app.querystring.tests.testRegistryReader.TestRegistryReader.test_get_vocabularies)
Traceback (most recent call last):
  File "/usr/lib64/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/usr/lib64/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "/usr/lib64/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
  File "plone.app.querystring/plone/app/querystring/tests/testRegistryReader.py", line 73, in test_get_vocabularies
    registry = self.createRegistry(td.test_vocabulary_xml)
  File "plone.app.querystring/plone/app/querystring/tests/testRegistryReader.py", line 47, in createRegistry
    importer.importDocument(xml)
  File "plone.app.querystring/.tox/test/lib/python3.11/site-packages/plone/app/registry/exportimport/handler.py", line 109, in importDocument
    tree = etree.fromstring(document)
  File "src/lxml/etree.pyx", line 3257, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1911, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

🍀

### CODE REVIEW

**Review by jensens — APPROVED** [review]

**Review by mauritsvanrees — APPROVED** [review]
LGTM, thanks.

> Should we adapt the tests to parse the files as bytes, or rather should zpretty not add those utf-8 encoding declarations? 🤔

I added a commit to turn the test inputs into bytes first, then it works.

**Comment by mauritsvanrees** [comment]
I am running PR tests for these three together:

- https://github.com/plone/plone.app.querystring/pull/121
- https://github.com/plone/plone.portlet.collection/pull/37
- https://github.com/plone/plone.scale/pull/74

**Comment by mauritsvanrees** [comment]
Jenkins passes, but the gh-actions tests fail, also locally:

```
Failure in test test__navigationPath (plone.app.querystring.tests.testQueryParser.TestQueryGenerators)
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.querystring/plone/app/querystring/tests/testQueryParser.py", line 535, in test__navigationPath
    self.assertEqual(parsed, expected)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 1144, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: {'path': {'query': ['//bar/']}} != {'path': {'query': ['/site/foo/bar/']}}
- {'path': {'query': ['//bar/']}}
+ {'path': {'query': ['/site/foo/bar/']}}
?                       ++++++++

```

**Comment by mauritsvanrees** [comment]
Ah, right, we need a new release of `plone.app.layout` in 6.0-dev.  I will see to that.

**Pull request merged**
