### PR TITLE
Filter query string from bad term and operator [technicalmanager@gmai…

### PR DESCRIPTION
**Pull request by nngu6036**
…l.com]

### CODE REVIEW

**Comment by thet** [comment]
I would prefer if we could reuse the functions and methods from https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/search.py - although that would mean to factor out the necessary methods from the browserview. maybe even moving them to Products.CMFPlone.utils (just an idea).
What do you think?

**Comment by nngu6036** [comment]
I used to have a look at  https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/search.py <https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/search.py> - and see these method do more thing than we need in plone.app.querystring, that is why I just made a copy and modified a bit to adapt to plone.app.querystring. I think you suggestion of putting that code inside the utils is good.

**Comment by jensens** [comment]
What about merging this one and then improving in a next step?

**Comment by thet** [comment]
+1, lets do that. Also, if the code in cmfplone does more than we need, an adapted copy is fine.

**Pull request merged**
