### PR TITLE
Add user vocabulary

### PR DESCRIPTION
**Pull request by vangheem**
\cc @mauritsvanrees

### CODE REVIEW

**Comment by vangheem** [comment]
tests running here: http://jenkins.plone.org/job/pull-request-5.0/229/

**Comment by vangheem** [comment]
@mauritsvanrees if you want to work on the vocabulary not using the Creator index, that is fine but this is a quick fix of how it can work with current available vocabs.

**Comment by mauritsvanrees** [comment]
Perfect, thanks.
I did some small extra changes.
I might have fixed the Jenkins robot failure in p.a.contenttypes (and with that broken current coredev 5.0).  I'm looking into that.
Meanwhile let's give Jenkins another go:
http://jenkins.plone.org/job/pull-request-5.0/230/

**Comment by mauritsvanrees** [comment]
Ugh. It's probably safe to merge the above now, it is much better than there currently is, but there is a problem.

For Creator you can choose 'Any' or 'Current logged in user'. If you select 'Any', or it is the default, you change your mind and select 'Current logged in user' and try to save, it fails and displays an error message in the browser: 'Wrong contained type'. Previously, before all the changes of today, we did not have 'Any', but 'Is', which was simply a string, which did not have this problem.

I first thought the newly added vocabulary was the problem, but that is not the case. I have reversed the order in registry.xml so that Current user is the top operator, and that helps.

@vangheem Can mockup in the case of 'Current logged in user' suppress submitting the value and only submit the index and operator? Or something to that effect?

Meanwhile, new Jenkins try:
http://jenkins.plone.org/job/pull-request-5.0/231/

**Pull request merged**
