### PR TITLE
Issue #97 i.e. allow for MultiPath Queries

### PR DESCRIPTION
**Pull request by gogobd**
fixing issue #97

### CODE REVIEW

**Comment by gogobd** [comment]
@jenkins-plone-org please run jobs

**Comment by gogobd** [comment]
This PR just manages MultiPath Queries - it parses through all of them and allows multiple translation groups.

**Comment by jensens** [comment]
See my PR #99 for a more generic solution

**Comment by gogobd** [comment]
@jenkins-plone-org please run jobs

**Comment by gogobd** [comment]
@jenkins-plone-org please run jobs

**Comment by gogobd** [comment]
@jenkins-plone-org please run jobs

**Comment by gogobd** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
